sonar.projectKey=Team-Haruki_Haruki-Sekai-API
sonar.organization=team-haruki
sonar.projectVersion=6.17.0
sonar.sourceEncoding=UTF-8
sonar.exclusions=Data/**,src/models/**
sonar.coverage.exclusions=ent_schemas/generated/**,src/db.rs,src/db/entity/**,src/logging.rs,src/main.rs,src/bin/**
sonar.rust.lcov.reportPaths=lcov.info
sonar.qualitygate.wait=true
