-- Apply to CN08 haruki_sekai BEFORE deploying the updated master_ingest.
-- Inspect existing table owners first; create both tables as haruki_sekai.
-- Source files exist in all five regions. TW/CN rows have no
-- mysekaiSiteHarvestFixtureId, so that column stays NULL there.
SET ROLE haruki_sekai;
BEGIN;
CREATE TABLE IF NOT EXISTS birthdayparties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    game_character_unit_id bigint,
    start_at bigint,
    birthday_start_at bigint,
    closed_at bigint,
    delivery_item_material_id bigint,
    delivery_reward_mysekai_material_id bigint,
    mysekai_site_harvest_spawn_limited_relation_group_id bigint,
    assetbundle_name character varying,
    mysekai_site_harvest_fixture_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS birthdayparty_game_id_server_region
    ON birthdayparties (game_id, server_region);
CREATE TABLE IF NOT EXISTS birthdaypartydeliverytotalrewards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    birthday_party_id bigint,
    requirement bigint,
    resource_box_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS birthdaypartydeliverytotalreward_game_id_server_region
    ON birthdaypartydeliverytotalrewards (game_id, server_region);
COMMIT;
RESET ROLE;
