-- Apply to CN08 haruki_sekai BEFORE deploying the updated master_ingest.
-- Inspect existing table owners first; create both tables as haruki_sekai.
-- Source files exist in all five regions. Blueprint shops have no game ID.
SET ROLE haruki_sekai;
BEGIN;
CREATE TABLE IF NOT EXISTS mysekaiblueprintshops (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mysekai_blueprint_shop_item_lottery_type character varying,
    consume_jewel_quantity bigint,
    purchase_limit bigint,
    server_region character varying NOT NULL
);
-- Ent/Atlas shortens PostgreSQL index names over 63 bytes to prefix + MD5.
CREATE UNIQUE INDEX IF NOT EXISTS mysekaiblueprintshop_mysekai_b_e45523b2171dffff402a4b44a9008d3f
    ON mysekaiblueprintshops (mysekai_blueprint_shop_item_lottery_type, server_region);
CREATE TABLE IF NOT EXISTS mysekaimaterialpossessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    level bigint,
    possession_limit bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaimaterialpossession_game_id_server_region
    ON mysekaimaterialpossessions (game_id, server_region);
COMMIT;
RESET ROLE;
