-- playerFrameParts: the per-character parts of JP's combination player frames.
-- Haruki-Cloud resolves a combination frame (playerFrameType "combination", e.g.
-- frame 20002) by mapping each partsLayout gameCharacterId to its part id through
-- this table; without it every combination frame renders as no frame.
-- Apply to the master database BEFORE deploying the updated master_ingest.
-- Preflight: connect as a role allowed to SET ROLE haruki_sekai. Only JP ships
-- the file (Nuverse 6.4 and EN 6.0 have single frames only).
-- psql "$DSN" -v ON_ERROR_STOP=1 -f docs/migrations/2026-10-01-player-frame-parts.sql

SET ROLE haruki_sekai;
BEGIN;

CREATE TABLE IF NOT EXISTS playerframeparts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    seq bigint,
    player_frame_group_id bigint,
    game_character_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS playerframepart_game_id_server_region ON playerframeparts (game_id, server_region);

COMMIT;

RESET ROLE;
