-- MySekai tools, sites and character talk pre-actions (JP 7.0 follow-ups).
-- Apply to the master database BEFORE deploying the updated master_ingest.
-- Preflight: inspect existing table owners and connect as a role allowed to
-- SET ROLE haruki_sekai. This creates all three tables owned by haruki_sekai.
-- The source files already exist in all five regions; absent optional fields
-- remain NULL. No app version or Nuverse schema configuration changes are needed.
-- psql "$DSN" -v ON_ERROR_STOP=1 -f docs/migrations/2026-09-30-mysekai-followups.sql

SET ROLE haruki_sekai;
BEGIN;

CREATE TABLE IF NOT EXISTS mysekaicharactertalkpreactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_character_talk_id bigint,
    mysekai_character_talk_tweet_id bigint,
    mysekai_character_talk_fixture_timeline_group_id bigint,
    mysekai_character_talk_free_timeline_group_id bigint,
    mysekai_character_talk_fixture_together_communication_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaicharactertalkpreaction_game_id_server_region ON mysekaicharactertalkpreactions (game_id, server_region);

CREATE TABLE IF NOT EXISTS mysekaisites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_site_type character varying,
    mysekai_site_category character varying,
    assetbundle_name character varying,
    name character varying,
    position_x bigint,
    position_y bigint,
    position_z bigint,
    is_base boolean,
    is_enabled_for_multi boolean,
    preset_group_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaisite_game_id_server_region ON mysekaisites (game_id, server_region);

CREATE TABLE IF NOT EXISTS mysekaitools (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    seq bigint,
    mysekai_tool_type character varying,
    tool_level bigint,
    name character varying,
    pronunciation character varying,
    description character varying,
    assetbundle_name character varying,
    sprite_name character varying,
    attack_power bigint,
    max_durability bigint,
    cool_time_micro_seconds double precision,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaitool_game_id_server_region ON mysekaitools (game_id, server_region);

COMMIT;
RESET ROLE;
