-- JP client 7.0.0 master schema (Haruki-Sekai-API feat/jp-700-master-schema).
--
-- Target: the master database the ingester writes (CN08 PostgreSQL, database
-- haruki_sekai). Ingest runs with create_tables: false there, and a schema_info.json
-- table missing from the database aborts the whole region's prepare, so this must be
-- applied BEFORE master_ingest is deployed with the new schema_info.json.
--
-- Idempotent: every statement is IF NOT EXISTS, so re-running is a no-op. Additive
-- only: no existing column, type or index changes. New columns stay NULL for regions
-- (and older rows) that do not ship the field.
--
-- Shape matches what Haruki-Cloud's ent migration creates for the generated schemas in
-- ent_schemas/generated/ (identity bigint id, character varying strings, jsonb nested
-- values, NOT NULL server_region, unique index <schema>_game_id_server_region), so a
-- later ent auto-migrate sees nothing to change.
--
-- Run as a role that can SET ROLE haruki_sekai (tables must be owned by haruki_sekai):
--   psql "$DSN" -v ON_ERROR_STOP=1 -f docs/migrations/2026-09-30-jp-700.sql
-- Preflight: the existing tables altered below must already be owned by haruki_sekai:
--   SELECT tablename, tableowner FROM pg_tables WHERE schemaname = 'public'
--     AND tablename IN ('areas','honorgroups','materials','mysekaigates',
--                       'mysekaisiteharvestfixtures','virtuallives');

SET ROLE haruki_sekai;

BEGIN;

-- New columns on existing tables
ALTER TABLE areas ADD COLUMN IF NOT EXISTS name2 character varying;
ALTER TABLE areas ADD COLUMN IF NOT EXISTS evolve_release_condition_id1 bigint;
ALTER TABLE areas ADD COLUMN IF NOT EXISTS evolve_release_condition_id2 bigint;
ALTER TABLE honorgroups ADD COLUMN IF NOT EXISTS is_medal_displayed boolean;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS expired_at bigint;
ALTER TABLE mysekaigates ADD COLUMN IF NOT EXISTS mysekai_gate_type character varying;
ALTER TABLE mysekaisiteharvestfixtures ADD COLUMN IF NOT EXISTS mysekai_site_bulk_harvest_target_id bigint;
ALTER TABLE virtuallives ADD COLUMN IF NOT EXISTS virtual_live_total_cheer_point_rewards jsonb;
ALTER TABLE virtuallives ADD COLUMN IF NOT EXISTS virtual_live_total_cheer_point_surplus_reward jsonb;
ALTER TABLE virtuallives ADD COLUMN IF NOT EXISTS virtual_live_virtual_item_override_cost jsonb;

-- New tables, JP 7.0.0 only for now (the other regions add them on their 7.0 update)

-- honorbackgrounds
CREATE TABLE IF NOT EXISTS honorbackgrounds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    seq bigint,
    honor_group_id bigint,
    assetbundle_name character varying,
    name character varying,
    description character varying,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS honorbackground_game_id_server_region ON honorbackgrounds (game_id, server_region);

-- honorwords
CREATE TABLE IF NOT EXISTS honorwords (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    seq bigint,
    honor_group_id bigint,
    assetbundle_name character varying,
    name character varying,
    description character varying,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS honorword_game_id_server_region ON honorwords (game_id, server_region);

-- mysekaiblueprinttermmysekaimaterialcosts
CREATE TABLE IF NOT EXISTS mysekaiblueprinttermmysekaimaterialcosts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    group_id bigint,
    mysekai_material_id bigint,
    seq bigint,
    quantity bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaiblueprinttermmysekaimaterialcost_game_id_server_region ON mysekaiblueprinttermmysekaimaterialcosts (game_id, server_region);

-- mysekaishopcosts
CREATE TABLE IF NOT EXISTS mysekaishopcosts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_shop_id bigint,
    seq bigint,
    resource_type character varying,
    resource_id bigint,
    quantity bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaishopcost_game_id_server_region ON mysekaishopcosts (game_id, server_region);

-- mysekaishops
CREATE TABLE IF NOT EXISTS mysekaishops (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_shop_type character varying,
    seq bigint,
    resource_box_id bigint,
    mysekai_shop_exchange_limit_type character varying,
    mysekai_shop_exchange_limit_value bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaishop_game_id_server_region ON mysekaishops (game_id, server_region);

-- mysekaisitebulkharvests
CREATE TABLE IF NOT EXISTS mysekaisitebulkharvests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_site_id bigint,
    mysekai_site_bulk_harvest_target_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaisitebulkharvest_game_id_server_region ON mysekaisitebulkharvests (game_id, server_region);

-- mysekaisitebulkharvesttargetgroups
CREATE TABLE IF NOT EXISTS mysekaisitebulkharvesttargetgroups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    seq bigint,
    name character varying,
    required_tool_id bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaisitebulkharvesttargetgroup_game_id_server_region ON mysekaisitebulkharvesttargetgroups (game_id, server_region);

-- mysekaisitebulkharvesttargets
CREATE TABLE IF NOT EXISTS mysekaisitebulkharvesttargets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_site_bulk_harvest_target_group_id bigint,
    seq bigint,
    name character varying,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaisitebulkharvesttarget_game_id_server_region ON mysekaisitebulkharvesttargets (game_id, server_region);

-- Tables every region ships that were never modeled; 7.0.0 features read them

-- mysekaiblueprintterms
CREATE TABLE IF NOT EXISTS mysekaiblueprintterms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    mysekai_blueprint_id bigint,
    start_at bigint,
    end_at bigint,
    mysekai_blueprint_term_tab_type character varying,
    mysekai_blueprint_term_mysekai_material_cost_group_id bigint,
    craft_limit bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS mysekaiblueprintterm_game_id_server_region ON mysekaiblueprintterms (game_id, server_region);

-- panelmissioncampaigns
CREATE TABLE IF NOT EXISTS panelmissioncampaigns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    name character varying,
    assetbundle_name character varying,
    bgm_assetbundle_name character varying,
    selectable_limit bigint,
    start_at bigint,
    progress_end_at bigint,
    closed_at bigint,
    distribution_end_at bigint,
    information_id bigint,
    panel_mission_selection_type character varying,
    panel_mission_sheet_groups jsonb,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS panelmissioncampaign_game_id_server_region ON panelmissioncampaigns (game_id, server_region);

-- virtualitems
CREATE TABLE IF NOT EXISTS virtualitems (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    virtual_item_category character varying,
    seq bigint,
    priority bigint,
    name character varying,
    assetbundle_name character varying,
    cost_virtual_coin bigint,
    cost_jewel bigint,
    effect_assetbundle_name character varying,
    effect_expression_type character varying,
    virtual_item_label_type character varying,
    start_at bigint,
    end_at bigint,
    game_character_unit_id bigint,
    unit character varying,
    sub_game_character_id bigint,
    virtual_item_type character varying,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS virtualitem_game_id_server_region ON virtualitems (game_id, server_region);

-- virtuallivegroups
CREATE TABLE IF NOT EXISTS virtuallivegroups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint,
    name character varying,
    virtual_live_group_type character varying,
    assetbundle_name character varying,
    start_at bigint,
    end_at bigint,
    server_region character varying NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS virtuallivegroup_game_id_server_region ON virtuallivegroups (game_id, server_region);

COMMIT;

RESET ROLE;
