{{- if and .Values.persistence.accounts.enabled (not .Values.persistence.accounts.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "haruki.accountsClaimName" . }}
  labels:
    {{- include "haruki.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - {{ .Values.persistence.accounts.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.accounts.size | quote }}
  {{- if .Values.persistence.accounts.storageClass }}
  storageClassName: {{ .Values.persistence.accounts.storageClass | quote }}
  {{- end }}
{{- end }}
