"""Generate the MySekai follow-up models from an Il2Cpp dump.cs.

Source: middlered/sekay v7.0.0_ios, il2cpp_analysis.zip/dump/dump.cs.
Run from any directory: python3 tools/generate_mysekai_followups.py /path/to/dump.cs
Then run tools/ent_generator and copy schema_info_generated.json to schema_info.json.
"""

import argparse
import pathlib
import re


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dump", type=pathlib.Path)
    args = parser.parse_args()
    source = args.dump.read_text()
    root = pathlib.Path(__file__).resolve().parents[1]
    types = {"int": "i64", "float": "f64", "string": "String", "bool": "bool"}
    outputs = {}
    for name in ("MysekaiTool", "MysekaiSite", "MysekaiCharacterTalkPreAction"):
        match = re.search(
            rf"^public class Master{name}\b[^\n]*\n\{{\n(.*?)^\}}",
            source,
            re.MULTILINE | re.DOTALL,
        )
        if match is None:
            raise ValueError(f"Missing Master{name}")
        fields = re.findall(
            r'\[Key\("([^"\n]+)"\)\]\s+public (\w+) \w+;', match[1]
        )
        if not fields or fields[0] != ("id", "int"):
            raise ValueError(f"Unexpected fields for Master{name}")
        alias = name.capitalize()
        body = []
        for key, kind in fields:
            snake = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
            body.append(f"    pub {snake}: Option<{types[kind]}>,")
        outputs[root / "src/models" / f"{name.lower()}s.rs"] = (
            "// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.\n"
            "use serde::{Deserialize, Serialize};\n\n"
            f"pub type {alias} = Vec<{alias}Element>;\n\n"
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n"
            '#[serde(rename_all = "camelCase")]\n'
            f"pub struct {alias}Element {{\n" + "\n\n".join(body) + "\n}\n"
        )
    for path, content in outputs.items():
        path.write_text(content)


if __name__ == "__main__":
    main()
