"""Generate the MySekai follow-up models from an Il2Cpp dump.cs.

Source: middlered/sekay v7.0.0_ios, il2cpp_analysis.zip/dump/dump.cs.
Run from the extracted archive directory (containing dump/dump.cs):
python3 /path/to/repository/tools/generate_mysekai_followups.py [--source "JP 7.0.0"]
Then run tools/ent_generator and copy schema_info_generated.json to schema_info.json.
"""

import argparse
import pathlib
import re


OUTPUT_DIR = pathlib.Path(__file__).resolve().parents[1] / "src/models"


DEFAULT_SOURCE = "JP 7.0.0"


def model_file_stem(name):
    """Pluralize the lowercased class name like tools/ent_generator names the table."""
    stem = name.lower()
    if stem.endswith("y") and stem[-2:] not in ("ay", "ey", "oy", "uy"):
        return f"{stem[:-1]}ies"
    return f"{stem}s"


def generate_models(source, source_label=DEFAULT_SOURCE):
    types = {"int": "i64", "long": "i64", "float": "f64", "string": "String", "bool": "bool"}
    outputs = {}
    identities = {
        "MysekaiTool": ("id", "int"),
        "MysekaiSite": ("id", "int"),
        "MysekaiCharacterTalkPreAction": ("id", "int"),
        "MysekaiBlueprintShop": ("mysekaiBlueprintShopItemLotteryType", "string"),
        "MysekaiMaterialPossession": ("id", "int"),
        "BirthdayParty": ("id", "int"),
        "BirthdayPartyDeliveryTotalReward": ("id", "int"),
    }
    for name, identity in identities.items():
        match = re.search(
            rf"^public class Master{name}\b[^\n]*\n\{{\n(.*?)^\}}",
            source,
            re.MULTILINE | re.DOTALL,
        )
        if match is None:
            raise ValueError(f"Missing Master{name}")
        fields = re.findall(
            r'\[Key\("([^"\n]+)"\)\]\s+public (\w+) \w+;', match[1]
        )
        if not fields or fields[0] != identity:
            raise ValueError(f"Unexpected fields for Master{name}")
        alias = name.capitalize()
        body = []
        for key, kind in fields:
            snake = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
            body.append(f"    pub {snake}: Option<{types[kind]}>,")
        outputs[f"{model_file_stem(name)}.rs"] = (
            f"// Generated by tools/generate_mysekai_followups.py from {source_label} dump.cs.\n"
            "use serde::{Deserialize, Serialize};\n\n"
            f"pub type {alias} = Vec<{alias}Element>;\n\n"
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n"
            '#[serde(rename_all = "camelCase")]\n'
            f"pub struct {alias}Element {{\n" + "\n\n".join(body) + "\n}\n"
        )
    return outputs


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", default=DEFAULT_SOURCE, help="client build named in the model headers")
    args = parser.parse_args(argv)
    source = (pathlib.Path.cwd() / "dump/dump.cs").read_text(encoding="utf-8")
    outputs = generate_models(source, args.source)
    for name, content in outputs.items():
        (OUTPUT_DIR / name).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
