"""Generate the MySekai follow-up models from an Il2Cpp dump.cs.

Source: middlered/sekay v7.0.0_ios, il2cpp_analysis.zip/dump/dump.cs.
Run from the extracted archive directory (containing dump/dump.cs):
python3 /path/to/repository/tools/generate_mysekai_followups.py
Then run tools/ent_generator and copy schema_info_generated.json to schema_info.json.
"""

import pathlib
import re


OUTPUT_DIR = pathlib.Path(__file__).resolve().parents[1] / "src/models"


def generate_models(source):
    types = {"int": "i64", "float": "f64", "string": "String", "bool": "bool"}
    outputs = {}
    identities = {
        "MysekaiTool": ("id", "int"),
        "MysekaiSite": ("id", "int"),
        "MysekaiCharacterTalkPreAction": ("id", "int"),
        "MysekaiBlueprintShop": ("mysekaiBlueprintShopItemLotteryType", "string"),
        "MysekaiMaterialPossession": ("id", "int"),
    }
    for name, identity in identities.items():
        match = re.search(
            rf"^public class Master{name}\b[^\n]*\n\{{\n(.*?)^\}}",
            source,
            re.MULTILINE | re.DOTALL,
        )
        if match is None:
            raise ValueError(f"Missing Master{name}")
        fields = re.findall(
            r'\[Key\("([^"\n]+)"\)\]\s+public (\w+) \w+;', match[1]
        )
        if not fields or fields[0] != identity:
            raise ValueError(f"Unexpected fields for Master{name}")
        alias = name.capitalize()
        body = []
        for key, kind in fields:
            snake = re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()
            body.append(f"    pub {snake}: Option<{types[kind]}>,")
        outputs[f"{name.lower()}s.rs"] = (
            "// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.\n"
            "use serde::{Deserialize, Serialize};\n\n"
            f"pub type {alias} = Vec<{alias}Element>;\n\n"
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n"
            '#[serde(rename_all = "camelCase")]\n'
            f"pub struct {alias}Element {{\n" + "\n\n".join(body) + "\n}\n"
        )
    return outputs


def main():
    source = (pathlib.Path.cwd() / "dump/dump.cs").read_text(encoding="utf-8")
    outputs = generate_models(source)
    for name, content in outputs.items():
        (OUTPUT_DIR / name).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
