// Generated by tools/generate_mysekai_followups.py from JP 6.8.1 iOS dump.cs.
use serde::{Deserialize, Serialize};

pub type Birthdayparty = Vec<BirthdaypartyElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BirthdaypartyElement {
    pub id: Option<i64>,

    pub game_character_unit_id: Option<i64>,

    pub start_at: Option<i64>,

    pub birthday_start_at: Option<i64>,

    pub closed_at: Option<i64>,

    pub delivery_item_material_id: Option<i64>,

    pub delivery_reward_mysekai_material_id: Option<i64>,

    pub mysekai_site_harvest_spawn_limited_relation_group_id: Option<i64>,

    pub assetbundle_name: Option<String>,

    pub mysekai_site_harvest_fixture_id: Option<i64>,
}
