// Generated by tools/generate_mysekai_followups.py from JP 6.8.1 iOS dump.cs.
use serde::{Deserialize, Serialize};

pub type Birthdaypartydeliverytotalreward = Vec<BirthdaypartydeliverytotalrewardElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BirthdaypartydeliverytotalrewardElement {
    pub id: Option<i64>,

    pub birthday_party_id: Option<i64>,

    pub requirement: Option<i64>,

    pub resource_box_id: Option<i64>,
}
