// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.
use serde::{Deserialize, Serialize};

pub type Mysekaiblueprintshop = Vec<MysekaiblueprintshopElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MysekaiblueprintshopElement {
    pub mysekai_blueprint_shop_item_lottery_type: Option<String>,

    pub consume_jewel_quantity: Option<i64>,

    pub purchase_limit: Option<i64>,
}
