// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.
use serde::{Deserialize, Serialize};

pub type Mysekaitool = Vec<MysekaitoolElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MysekaitoolElement {
    pub id: Option<i64>,

    pub seq: Option<i64>,

    pub mysekai_tool_type: Option<String>,

    pub tool_level: Option<i64>,

    pub name: Option<String>,

    pub pronunciation: Option<String>,

    pub description: Option<String>,

    pub assetbundle_name: Option<String>,

    pub sprite_name: Option<String>,

    pub attack_power: Option<i64>,

    pub max_durability: Option<i64>,

    pub cool_time_micro_seconds: Option<f64>,
}
