// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.
use serde::{Deserialize, Serialize};

pub type Mysekaimaterialpossession = Vec<MysekaimaterialpossessionElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MysekaimaterialpossessionElement {
    pub id: Option<i64>,

    pub level: Option<i64>,

    pub possession_limit: Option<i64>,
}
