// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.
use serde::{Deserialize, Serialize};

pub type Mysekaisite = Vec<MysekaisiteElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MysekaisiteElement {
    pub id: Option<i64>,

    pub mysekai_site_type: Option<String>,

    pub mysekai_site_category: Option<String>,

    pub assetbundle_name: Option<String>,

    pub name: Option<String>,

    pub position_x: Option<i64>,

    pub position_y: Option<i64>,

    pub position_z: Option<i64>,

    pub is_base: Option<bool>,

    pub is_enabled_for_multi: Option<bool>,

    pub preset_group_id: Option<i64>,
}
