// Generated by tools/generate_mysekai_followups.py from JP 7.0.0 dump.cs.
use serde::{Deserialize, Serialize};

pub type Mysekaicharactertalkpreaction = Vec<MysekaicharactertalkpreactionElement>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MysekaicharactertalkpreactionElement {
    pub id: Option<i64>,

    pub mysekai_character_talk_id: Option<i64>,

    pub mysekai_character_talk_tweet_id: Option<i64>,

    pub mysekai_character_talk_fixture_timeline_group_id: Option<i64>,

    pub mysekai_character_talk_free_timeline_group_id: Option<i64>,

    pub mysekai_character_talk_fixture_together_communication_id: Option<i64>,
}
